version: '3'

services:
  
  portainer_gnl:
    image: portainer/portainer-ce
    container_name: portainer_gnl
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

